---
- name: Example Playbook
  hosts: localhost
  tasks:
    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: present
        
    - name: Get current time
      ansible.builtin.command: date
      register: current_time

    - name: Display current time
      ansible.builtin.debug:
        msg: "Current time on CentOS container is {{ current_time.stdout }}"

