name: Test Playbook on CentOS 7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged   # Needed to run Docker within Docker

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Docker image for testing
      run: |
        docker build -t ansible-test - <<EOF
        FROM centos:7
        RUN yum -y install epel-release && \
            yum -y install ansible python3-pip && \
            yum clean all && \
            pip3 install --no-cache-dir docker
        EOF

    - name: Run playbook in CentOS 7 container
      run: |
        docker run --rm -v $(pwd):/ansible -w /ansible ansible-test ansible-playbook example.yml

    # Add additional steps as needed, such as running tests or reporting results.
